### PR TITLE
Add language switcher markup

### PR DESCRIPTION
**Pull request by fabian**
@TehWazzard as discussed on Wrike, let's work on the branch `language-switcher` on this implementation. This commit adds just the mockup markup, we still need to figure out how to do the implementation so the application can define which languages are available etc.

### CODE REVIEW

**Comment by TehWazzard** [comment]
I've made a couple changes to the branch:

- Input parameter for languages
- Output event when a language is selected
- introduced `active` class on selected or default language

would you mind having a look at the CSS, see if the active class looks good.

I'll build the helper methods for language selection this week. right now we could release this as-is as a phase 1. applications will not need to specify any input - english has been set to the default.

**Comment by fabian** [comment]
@TehWazzard I've remove the `defaultLanguages` and instead hide the language selector if no languages are provided, okay?

@RajeevSiewnath Can you review this PR? Would this work for the language implementation in People?

**Comment by TehWazzard** [comment]
Looks good to me.

**Comment by RajeevSiewnath** [comment]
Looks good indeed. I would have maybe chosen for a LanguageModelInterface interface type rather than a class type since the class doesn't add anything here and it would be easier to just drop in plain object that adhere to a interface. But that's just nitpicking :)

**Comment by TehWazzard** [comment]
Perfect - if you guys are happy I can bump the version and release (I can switch the model to an interface too)

**Comment by RajeevSiewnath** [comment]
Great! I’m happy :)

**Comment by fabian** [comment]
Good to release, thanks for the interface change!

**Pull request merged**
